
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DcSergio
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        getRootPane().putClientProperty("JRootPane.titleBarBackground", new Color(0,0,0));
        getRootPane().putClientProperty("JRootPane.titleBarForeground", Color.red);
        setUndecorated(true);
        initComponents();
        incorrecto1.setText("");
        incorrecto2.setText("");
        sumandoUno.setHorizontalAlignment(JTextField.CENTER);
        sumandoDos.setHorizontalAlignment(JTextField.CENTER);
        suma.setHorizontalAlignment(JTextField.CENTER);
        
        ImageIcon imageIcon = new ImageIcon("/minus-32.png"); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(30, 30,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);
        
        sumandoUno.requestFocus();
        suma.setFocusable(false);
        //jLabel3.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator.png")).getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH)));
            //minimizar.setIcon(imageIcon); // NOI18N
            //minimizar.setOpaque(false);
            //minimizar.setContentAreaFilled(false);
            //minimizar.setBorderPainted(false);
            //minimizar.setBorder(BorderFactory.createEmptyBorder());
            //minimizar.setBorderPainted(false);
            //minimizar.setFocusPainted(false);
            //minimizar.setContentAreaFilled(false);
            
            //salir.setBorderPainted(false);
            //salir.setFocusPainted(false);
            //salir.setContentAreaFilled(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        sumandoUno = new javax.swing.JTextField();
        sumandoDos = new javax.swing.JTextField();
        suma = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        incorrecto2 = new javax.swing.JLabel();
        incorrecto1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 51, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setLocation(new java.awt.Point(800, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });

        sumandoUno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sumandoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumandoUnoActionPerformed(evt);
            }
        });
        sumandoUno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sumandoUnoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sumandoUnoKeyReleased(evt);
            }
        });

        sumandoDos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sumandoDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumandoDosActionPerformed(evt);
            }
        });
        sumandoDos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sumandoDosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sumandoDosKeyReleased(evt);
            }
        });

        suma.setEditable(false);
        suma.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Suma ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Calculadora");

        incorrecto2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        incorrecto2.setForeground(new java.awt.Color(255, 0, 0));
        incorrecto2.setText("Incorrecto");

        incorrecto1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        incorrecto1.setForeground(new java.awt.Color(255, 0, 0));
        incorrecto1.setText("Incorrecto");

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiply-2-16.png"))); // NOI18N
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salirFocusLost(evt);
            }
        });
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                salirMouseReleased(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        salir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salirKeyPressed(evt);
            }
        });

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minus-16.png"))); // NOI18N
        minimizar.setBorder(null);
        minimizar.setBorderPainted(false);
        minimizar.setContentAreaFilled(false);
        minimizar.setFocusPainted(false);
        minimizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                minimizarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                minimizarFocusLost(evt);
            }
        });
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                minimizarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                minimizarMouseReleased(evt);
            }
        });
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        minimizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                minimizarKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator.png")).getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH)));
        jLabel3.setText("Calculadora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(minimizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(incorrecto2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sumandoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(incorrecto1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sumandoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumandoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incorrecto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumandoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incorrecto2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sumandoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumandoUnoActionPerformed
        // TODO add your handling code here:    
    }//GEN-LAST:event_sumandoUnoActionPerformed

    private void sumandoDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumandoDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumandoDosActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumaActionPerformed

    private void sumandoDosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sumandoDosKeyPressed
        // TODO add your handling code here:
        String sum1 = sumandoUno.getText().trim();
        String sum2 = sumandoDos.getText().trim();
        
        int s1,s2;
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            if(sum1.equals("") && sum2.equals("")){
                sumandoUno.requestFocus();
                return;
            }
            s1 = esNumero(sum1, incorrecto1);
            s2 = esNumero(sum2, incorrecto2);
            if(s1<0 || s2<0){
                sum1Anterior = sum1;
                sum2Anterior = sum2;
                suma.setText("Sintax Error");
                if(!incorrecto1.getText().equals(""))
                    sumandoUno.requestFocus();
                else if(!incorrecto2.getText().equals(""))
                    sumandoDos.requestFocus();
                return;
            }
            suma.setText(Integer.toString(s1 + s2));
            sum1Anterior = sum1;
            sum2Anterior = sum2;
            sumandoUno.requestFocus();
                //return;
        }else if(sum2Anterior!=null && !sum2Anterior.equals(sum2))
            suma.setText("");
        
    }//GEN-LAST:event_sumandoDosKeyPressed

    private void sumandoUnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sumandoUnoKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            sumandoDos.requestFocus();
        }
    }//GEN-LAST:event_sumandoUnoKeyPressed

    private void sumandoDosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sumandoDosKeyReleased
        // TODO add your handling code here:
        String sum1 = sumandoUno.getText().trim();
        String sum2 = sumandoDos.getText().trim();
        
        double s1,s2;
        
        if(sum2Anterior!=null && !sum2Anterior.equals(sum2))
            suma.setText("");
        
        if(sum1.equals("") && sum2.equals("")){
            incorrecto1.setText("");
            incorrecto2.setText("");
            return;
        }
        s1 = esNumero(sum1, incorrecto1);
        s2 = esNumero(sum2, incorrecto2);
        if(!(s2<0))
            incorrecto2.setText("");
    }//GEN-LAST:event_sumandoDosKeyReleased

    private void sumandoUnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sumandoUnoKeyReleased
        // TODO add your handling code here:
        String sum1 = sumandoUno.getText().trim();
        String sum2 = sumandoDos.getText().trim();
        
        double s1,s2;
        if((sum1Anterior!=null && !sum1Anterior.equals(sum1)))
            suma.setText("");
        
        if(sum1.equals("") && sum2.equals("")){
            incorrecto1.setText("");
            incorrecto2.setText("");
            return;
        }
        s1 = esNumero(sum1, incorrecto1);
        s2 = esNumero(sum2, incorrecto2);
        if(!(s1<0))
            incorrecto1.setText("");
    }//GEN-LAST:event_sumandoUnoKeyReleased

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        // TODO add your handling code here:
        System.out.println(evt.getNewState());
        if(evt.getNewState() == 0)
            setVisible(false);
    }//GEN-LAST:event_formWindowIconified

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        // TODO add your handling code here:
        setState(javax.swing.JFrame.ICONIFIED);
        systemtray();
    }//GEN-LAST:event_minimizarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void minimizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMousePressed
        // TODO add your handling code here:
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON1)
            minimizar.setIcon(new ImageIcon(getClass().getResource("minus-16-white.png")));
    }//GEN-LAST:event_minimizarMousePressed

    private void minimizarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseReleased
        // TODO add your handling code here:
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON1)
            minimizar.setIcon(new ImageIcon(getClass().getResource("minus-16.png")));
    }//GEN-LAST:event_minimizarMouseReleased

    private void salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMousePressed
        // TODO add your handling code here:
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON1)
            salir.setIcon(new ImageIcon(getClass().getResource("multiply-2-16-white.png")));
    }//GEN-LAST:event_salirMousePressed

    private void salirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseReleased
        // TODO add your handling code here:
        if(evt.getButton() == java.awt.event.MouseEvent.BUTTON1)
            salir.setIcon(new ImageIcon(getClass().getResource("multiply-2-16.png")));
    }//GEN-LAST:event_salirMouseReleased
    private int posx;
    private int posy;
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        //System.out.println("Arrastrando");
        setLocation(getX()+(evt.getX()-posx), getY()+(evt.getY()-posy));
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        posx = evt.getX();
        posy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void minimizarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_minimizarFocusGained
        // TODO add your handling code here:
        minimizar.setIcon(new ImageIcon(getClass().getResource("minus-16-white.png")));
    }//GEN-LAST:event_minimizarFocusGained

    private void minimizarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_minimizarFocusLost
        // TODO add your handling code here:
        minimizar.setIcon(new ImageIcon(getClass().getResource("minus-16.png")));
    }//GEN-LAST:event_minimizarFocusLost

    private void salirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salirFocusGained
        // TODO add your handling code here:
        salir.setIcon(new ImageIcon(getClass().getResource("multiply-2-16-white.png")));
    }//GEN-LAST:event_salirFocusGained

    private void salirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salirFocusLost
        // TODO add your handling code here:
        salir.setIcon(new ImageIcon(getClass().getResource("multiply-2-16.png")));
    }//GEN-LAST:event_salirFocusLost

    private void minimizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minimizarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            setState(javax.swing.JFrame.ICONIFIED);
        systemtray();
    }//GEN-LAST:event_minimizarKeyPressed

    private void salirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salirKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
            System.exit(0);
    }//GEN-LAST:event_salirKeyPressed
    
    public void systemtray(){
        SystemTray systemTray = SystemTray.getSystemTray();
        TrayIcon trayIcon = new TrayIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("calculator.png")));
        trayIcon.setImageAutoSize(true);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("calculator.png")));
        PopupMenu popMenu = new PopupMenu();
        MenuItem show = new MenuItem("Abrir");
        show.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setExtendedState(javax.swing.JFrame.NORMAL);
                systemTray.remove(trayIcon);
                setVisible(true);
                sumandoUno.requestFocus();
            }
        });
        MenuItem exit = new MenuItem("Salir");
        exit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                systemTray.remove(trayIcon);
                System.exit(0);
            }
        });
        popMenu.add(show);
        popMenu.add(exit);
        trayIcon.setPopupMenu(popMenu);
        
        try {
            systemTray.add(trayIcon);
        } catch (AWTException ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public int esNumero(String sum,JLabel incorrecto){
        try {
            return Integer.parseInt(sum);
        } catch (NumberFormatException ex) {
            incorrecto.setText("Incorrecto");
            return -1;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try { 
            UIManager.put( "control", new Color( 0, 0, 0) );
            UIManager.put( "Button.background", new Color(18, 30, 49) );
            UIManager.put( "Button.foreground", new Color( 59, 68, 75) );
            UIManager.put( "info", new Color(128,128,128) );
            UIManager.put( "nimbusBase", new Color( 18, 30, 49) );
            UIManager.put( "nimbusAlertYellow", new Color( 248, 187, 0) );
            UIManager.put( "nimbusDisabledText", new Color( 128, 128, 128) );
            UIManager.put( "nimbusFocus", new Color(115,164,209) );
            UIManager.put( "nimbusGreen", new Color(176,179,50) );
            UIManager.put( "nimbusInfoBlue", new Color( 66, 139, 221) );
            UIManager.put( "nimbusLightBackground", new Color( 18, 30, 49) );
            UIManager.put( "nimbusOrange", new Color(191,98,4) );
            UIManager.put( "nimbusRed", new Color(169,46,34) );
            UIManager.put( "nimbusSelectedText", new Color( 255, 255, 255) );
            UIManager.put( "nimbusSelectionBackground", new Color( 104, 93, 156) );
            UIManager.put( "text", new Color( 255, 255, 255) );
            UIManager.put("TitlePane.unifiedBackground", false);
            
            UIManager.put("JFrame.activeTitleBackground", Color.red);
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }    
        } catch (Exception e) {
            System.err.println("Exception caught:"+e);               
        } 
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        javax.swing.JFrame.setDefaultLookAndFeelDecorated(true);
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    private String sum1Anterior;
    private String sum2Anterior;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel incorrecto1;
    private javax.swing.JLabel incorrecto2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton minimizar;
    private javax.swing.JButton salir;
    private javax.swing.JTextField suma;
    private javax.swing.JTextField sumandoDos;
    private javax.swing.JTextField sumandoUno;
    // End of variables declaration//GEN-END:variables
}
